_core:
  default_config_hash: _t4SDg8-MRfDCkRRB8YGy1EWX5GnkZasM1xZi4hpI4M
src: 'https://pfrill.ing/umami.js'
website_id: 'REDACTED'
host_url: ''
auto_track: true
do_not_track: false
cache: false
domain_mode: 0
domains: ''
visibility:
  request_path_mode: 0
  request_path_pages: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
  user_role_mode: 1
  user_role_roles:
    administrator: administrator
local_cache: false
